### ISSUE TITLE
How is that …

### ISSUE THREAD

**Issue by Mark2Mark** [mekkablue/ShowCenterLines#1]
… different from Show Smart Plumblines?

**Comment by mekkablue** [comment]
Was a specific request from a user who did not find Smart Plumblines an exact match for his needs
Not sure anymore what exactly it was, but I think it’s that it focuses on the selection bbox, not paths.

**Comment by Mark2Mark** [comment]
Smart Plumblines focusses on any selection, hence the selection box, and/or paths, components, anchors …

Still don’t see a difference and find it confusing to have 2 so similar plugins out there.

Why did that person or you not ask me to implement that mystical feature?
